### ISSUE TITLE
Can't Recognize codechecker installed by snap

### ISSUE THREAD

**Issue by LWSG** [Ericsson/CodecheckerVSCodePlugin#103] opened 2022-03-16 00:49 UTC
codechecker installed by snap is named 'codechecker', but 'CodeChecker' install by pip3.
Although config in Executable Path is set to ‘codechecker'

Console Output In vscode
```
>>> Starting process 'CodeChecker analyzer-version'
> codechecker analyzer-version --output json
>>> Process 'CodeChecker analyzer-version' exited with code 120
>>> CodeChecker error while checking version


```
In shell
```
❯ codechecker analyzer-version --output json
{"base_package_version": "6.19.0", "package_build_date": "2022-03-11T12:05", "git_commit": null, "git_tag": null}
❯ echo "$?"
0
```

**Comment by csordasmarton** [comment] 2022-03-17 11:07
@LWSG I was able to reproduce this problem with the following code and CodeChecker installed via snap:

```js
const child_process = require('child_process');

child_process
  .spawn('codechecker', ['analyzer-version', '--output', 'json'])
  .on("exit", (code) => {
    console.log("Exit code:", code);
  });
```

Output:
```
$ node test.js 
Exit code: 120
```

@Discookie Do you have any idea what is the problem here? I saw that in #104 you are using snap package to run test cases. How is it possible that it works for you?

**Comment by Discookie** [comment] 2022-03-17 12:32
From a quick search I could only find code 120 as a reference to https://bugs.python.org/issue29130 related to calling `flush()` in Python - looks to be a CodeChecker issue? Not sure, will need to test further

**Comment by LWSG** [comment] 2022-03-23 00:55
Yes, my vscode is installed by snap
```
//snap list code
Name  Version   Rev  Tracking       Publisher  Notes
code  c722ca6c  91   latest/stable  vscode*    classic
```

**Comment by LWSG** [comment] 2022-03-23 00:58
The problem is similar to the [issue](https://forum.snapcraft.io/t/node-snap-issues-with-exec-of-npm-node-yarn/23635), but 'codechecker' instead of 'npm', should I close the Issue?

**Comment by vodorok** [comment] 2022-07-01 09:06
Then the issue is with npm, therefore closing this one. Please reopen if needed.

**Closed by vodorok** 2022-07-01 09:06 UTC
Labels: bug, MEDIUM
