### ISSUE TITLE
Bug tree view and CodeLens shows different number of bug steps

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodecheckerVSCodePlugin#36] opened 2021-12-13 09:38 UTC
In the tree view for a division by zero error I see that I have 3 bug steps but on the source code CodeLens shows me an extra bug step.

**main.h**:
```h
#ifndef MAIN_H
#define MAIN_H

double foo(int param) {
  return 1 / param;
}

#endif
```

**main.cpp**:
```cpp
#include "main.h"

int main() {
  return foo(0);
}
```

![image](https://user-images.githubusercontent.com/6695818/144193280-cf2c23de-b798-4bec-887b-0d2d74cd9379.png)
![image](https://user-images.githubusercontent.com/6695818/144193309-9eeba43f-9e72-4249-a282-4b8e71c1e68c.png)

**Comment by Discookie** [comment] 2022-01-26 21:39
Cannot reproduce, most likely fixed by either #28 or #37.

Feel free to reopen the issue if you find any other files where this happens!

**Closed by Discookie** 2022-01-26 21:39 UTC
Labels: bug
